before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/usher/usher.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}-{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: nfpms
    description: usher is a tiny url shortener that manages a local db and pushes to various cloud backends
    maintainer: Gavin Carr <gavin@openfusion.com.au>
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: '{{ .ProjectName }}_{{ replace .Version "v" "" }}_{{ .Arch }}'
    overrides:
      rpm:
        file_name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}.{{ .Arch }}'
release:
  github:
    owner: gavincarr
    name: usher
env_files:
  github_token: ~/.gh_goreleaser
